name: Docker Image build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mazuninky/gradle-aws-docker
    - name: Login to Docker Hub
      env:
        GITHUB_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      run: docker login -u mazuninky -p $DOCKER_ACCESS_TOKEN
    - name: Push image
      run: docker push mazuninky/gradle-aws-docker
